# Generated by Django 5.2.8 on 2025-11-12 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Icon name (lucide-react)', max_length=50)),
                ('achievement_type', models.CharField(choices=[('quiz_master', 'Quiz Master'), ('speed_demon', 'Speed Demon'), ('battle_winner', 'Battle Winner'), ('explorer', 'Explorer'), ('first_quiz', 'First Quiz'), ('streak_master', 'Streak Master'), ('perfect_score', 'Perfect Score'), ('early_bird', 'Early Bird')], max_length=20)),
                ('xp_reward', models.IntegerField(default=50, help_text='XP thưởng khi đạt được')),
                ('requirement', models.JSONField(help_text='Điều kiện đạt được (JSON)')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuizBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_start_time', models.DateTimeField(help_text='Thời gian bắt đầu trận đấu')),
                ('duration_minutes', models.IntegerField(default=10, help_text='Thời gian làm bài (phút)')),
                ('status', models.CharField(choices=[('pending', 'Chờ bắt đầu'), ('in_progress', 'Đang diễn ra'), ('completed', 'Đã kết thúc'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('questions', models.JSONField(help_text='List of quiz IDs [quiz_id1, quiz_id2, ...]')),
                ('participants', models.JSONField(help_text='List of usernames [username1, username2, ...]')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('geojson', models.JSONField()),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('conservation_status', models.CharField(choices=[('critical', 'Critical - Nguy cấp'), ('watch', 'Watch - Cần quan tâm'), ('good', 'Good - Tốt')], default='good', max_length=20)),
                ('status_description', models.TextField(blank=True, help_text='Mô tả tình trạng bảo tồn')),
                ('conduct', models.JSONField(blank=True, default=dict, help_text="JSON format: {dos: [], donts: [], lawExcerpt: '', lawLink: ''}")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Tên người dùng', max_length=200, unique=True)),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh đại diện', null=True, upload_to='avatars/')),
                ('total_xp', models.IntegerField(default=0, help_text='Tổng số XP')),
                ('level', models.IntegerField(default=1, help_text='Cấp độ hiện tại')),
                ('display_name', models.CharField(blank=True, help_text='Tên hiển thị', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Tiểu sử')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_xp', '-level'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('xp_reward', models.IntegerField(default=10, help_text='Số điểm XP nhận được khi trả lời đúng')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='heritage.site')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='heritage.site')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_email', models.EmailField(default='admin@example.com', help_text='Email nhận phản hồi từ người dùng', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address của người dùng')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string từ browser')),
                ('path', models.CharField(help_text='URL path được truy cập', max_length=500)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP status code trả về')),
                ('response_time', models.FloatField(help_text='Thời gian xử lý request (giây)')),
                ('user_name', models.CharField(blank=True, help_text='Tên người dùng nếu đã đăng nhập', max_length=200)),
                ('session_id', models.CharField(blank=True, help_text='Session ID', max_length=100)),
                ('referrer', models.URLField(blank=True, help_text='URL referrer')),
                ('country', models.CharField(blank=True, help_text='Quốc gia (từ IP geolocation)', max_length=100)),
                ('city', models.CharField(blank=True, help_text='Thành phố', max_length=100)),
                ('user_agent_parsed', models.JSONField(blank=True, default=dict, help_text='Thông tin phân tích user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='heritage_us_ip_addr_1ee02f_idx'), models.Index(fields=['path', 'created_at'], name='heritage_us_path_ca0603_idx'), models.Index(fields=['user_name', 'created_at'], name='heritage_us_user_na_cc182f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Học sinh'), ('tourist', 'Khách du lịch'), ('teacher', 'Giáo viên'), ('super_admin', 'Super Admin')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='Tên lớp')),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='Tên trường')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('xp_earned', models.IntegerField(default=0, help_text='Số XP kiếm được (0 nếu sai)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='heritage.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'user_name')},
            },
        ),
        migrations.CreateModel(
            name='QuizBattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0, help_text='Tổng điểm')),
                ('correct_answers', models.IntegerField(default=0, help_text='Số câu đúng')),
                ('total_answered', models.IntegerField(default=0, help_text='Tổng số câu đã trả lời')),
                ('time_completed', models.IntegerField(blank=True, help_text='Tổng thời gian (giây)', null=True)),
                ('answers', models.JSONField(default=dict, help_text='Quiz ID -> {answer, is_correct, time_taken}')),
                ('rank', models.IntegerField(blank=True, help_text='Hạng (1-4)', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participants', to='heritage.quizbattle')),
            ],
            options={
                'ordering': ['-total_answered', '-correct_answers', 'time_completed'],
                'unique_together': {('battle', 'user_name')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Tên người dùng (tourist/student)', max_length=200)),
                ('content', models.TextField(help_text='Nội dung bình luận')),
                ('images', models.JSONField(blank=True, default=list, help_text='Danh sách URLs hình ảnh (tối đa 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_reported', models.BooleanField(default=False, help_text='Đã bị báo cáo')),
                ('report_count', models.IntegerField(default=0, help_text='Số lần báo cáo')),
                ('reported_by', models.JSONField(blank=True, default=list, help_text='Danh sách user đã báo cáo')),
                ('user', models.ForeignKey(blank=True, help_text='User đã đăng nhập (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='heritage.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', '-created_at'], name='heritage_co_site_id_39670f_idx'), models.Index(fields=['user_name', '-created_at'], name='heritage_co_user_na_dd649b_idx'), models.Index(fields=['is_reported'], name='heritage_co_is_repo_ce5e18_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='heritage.userprofile')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
