# Generated by Django 5.2.7 on 2025-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
