# Generated by Django 5.2.8 on 2025-11-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
    ]
