# Generated by Django 5.2.7 on 2025-10-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_site_image_url_site_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='image_url',
        ),
        migrations.AddField(
            model_name='site',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
