
# Generated by Django 5.2.7 on 2025-10-23 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0005_quiz_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'user_name')},
        ),
    ]
