# Generated by Django 5.2.7 on 2025-10-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0007_user_activity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Icon name (lucide-react)', max_length=50)),
                ('achievement_type', models.CharField(choices=[('quiz_master', 'Quiz Master'), ('speed_demon', 'Speed Demon'), ('battle_winner', 'Battle Winner'), ('explorer', 'Explorer'), ('first_quiz', 'First Quiz'), ('streak_master', 'Streak Master'), ('perfect_score', 'Perfect Score'), ('early_bird', 'Early Bird')], max_length=20)),
                ('xp_reward', models.IntegerField(default=50, help_text='XP thưởng khi đạt được')),
                ('requirement', models.JSONField(help_text='Điều kiện đạt được (JSON)')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Tên người dùng', max_length=200, unique=True)),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh đại diện', null=True, upload_to='avatars/')),
                ('total_xp', models.IntegerField(default=0, help_text='Tổng số XP')),
                ('level', models.IntegerField(default=1, help_text='Cấp độ hiện tại')),
                ('display_name', models.CharField(blank=True, help_text='Tên hiển thị', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Tiểu sử')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_xp', '-level'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=models.deletion.CASCADE, to='heritage.achievement')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='achievements', to='heritage.userprofile')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]