# Generated by Django 5.2.8 on 2025-11-10 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0011_userrole'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Comment',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('user_name', models.CharField(help_text='Tên người dùng (tourist/student)', max_length=200)),
        #         ('content', models.TextField(help_text='Nội dung bình luận')),
        #         ('images', models.JSONField(blank=True, default=list, help_text='Danh sách URLs hình ảnh')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('is_reported', models.BooleanField(default=False, help_text='Đã bị báo cáo')),
        #         ('report_count', models.IntegerField(default=0, help_text='Số lần báo cáo')),
        #         ('reported_by', models.JSONField(blank=True, default=list, help_text='Danh sách user đã báo cáo')),
        #     ],
        #     options={
        #         'ordering': ['-created_at'],
        #     },
        # ),
        # migrations.CreateModel(
        #     name='QuizBattle',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('scheduled_start_time', models.DateTimeField(help_text='Thời gian bắt đầu trận đấu')),
        #         ('duration_minutes', models.IntegerField(default=10, help_text='Thời gian làm bài (phút)')),
        #         ('status', models.CharField(choices=[('pending', 'Chờ bắt đầu'), ('in_progress', 'Đang diễn ra'), ('completed', 'Đã kết thúc'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
        #         ('questions', models.JSONField(help_text='List of quiz IDs [quiz_id1, quiz_id2, ...]')),
        #         ('participants', models.JSONField(help_text='List of usernames [username1, username2, ...]')),
        #     ],
        #     options={
        #         'ordering': ['-created_at'],
        #     },
        # ),
        # migrations.CreateModel(
        #     name='QuizBattleParticipant',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('user_name', models.CharField(max_length=200)),
        #         ('score', models.IntegerField(default=0, help_text='Tổng điểm')),
        #         ('correct_answers', models.IntegerField(default=0, help_text='Số câu đúng')),
        #         ('time_completed', models.IntegerField(blank=True, help_text='Tổng thời gian (giây)', null=True)),
        #         ('answers', models.JSONField(default=dict, help_text='Quiz ID -> {answer, is_correct, time_taken}')),
        #         ('rank', models.IntegerField(blank=True, help_text='Hạng (1-4)', null=True)),
        #         ('joined_at', models.DateTimeField(auto_now_add=True)),
        #         ('finished_at', models.DateTimeField(blank=True, null=True)),
        #     ],
        #     options={
        #         'ordering': ['-score', 'time_completed'],
        #     },
        # ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='heritage_us_ip_addr_1ee02f_idx',
            old_name='heritage_us_ip_addres_8b8b7a_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='heritage_us_path_ca0603_idx',
            old_name='heritage_us_path_4b8b7a_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='heritage_us_user_na_cc182f_idx',
            old_name='heritage_us_user_na_8b8b7a_idx',
        ),
        migrations.AddField(
            model_name='quiz',
            name='xp_reward',
            field=models.IntegerField(default=10, help_text='Số điểm XP nhận được khi trả lời đúng'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='xp_earned',
            field=models.IntegerField(default=0, help_text='Số XP kiếm được (0 nếu sai)'),
        ),
        migrations.AddField(
            model_name='site',
            name='conduct',
            field=models.JSONField(blank=True, default=dict, help_text="JSON format: {dos: [], donts: [], lawExcerpt: '', lawLink: ''}"),
        ),
        migrations.AddField(
            model_name='site',
            name='conservation_status',
            field=models.CharField(choices=[('critical', 'Critical - Nguy cấp'), ('watch', 'Watch - Cần quan tâm'), ('good', 'Good - Tốt')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='status_description',
            field=models.TextField(blank=True, help_text='Mô tả tình trạng bảo tồn'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên lớp'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên trường'),
        ),
        # migrations.AddField(
        #     model_name='comment',
        #     name='site',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='heritage.site'),
        # ),
        # migrations.AddField(
        #     model_name='quizbattleparticipant',
        #     name='battle',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participants', to='heritage.quizbattle'),
        # ),
        # migrations.AddIndex(
        #     model_name='comment',
        #     index=models.Index(fields=['site', '-created_at'], name='heritage_co_site_id_39670f_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='comment',
        #     index=models.Index(fields=['user_name', '-created_at'], name='heritage_co_user_na_dd649b_idx'),
        # ),
        # migrations.AddIndex(
        #     model_name='comment',
        #     index=models.Index(fields=['is_reported'], name='heritage_co_is_repo_ce5e18_idx'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='quizbattleparticipant',
        #     unique_together={('battle', 'user_name')},
        # ),
    ]
