# Generated by Django 5.2.8 on 2025-11-10 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0013_quizbattle_alter_userrole_role_systemsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_start_time', models.DateTimeField(help_text='Thời gian bắt đầu trận đấu')),
                ('duration_minutes', models.IntegerField(default=10, help_text='Thời gian làm bài (phút)')),
                ('status', models.CharField(choices=[('pending', 'Chờ bắt đầu'), ('in_progress', 'Đang diễn ra'), ('completed', 'Đã kết thúc'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('questions', models.JSONField(help_text='List of quiz IDs [quiz_id1, quiz_id2, ...]')),
                ('participants', models.JSONField(help_text='List of usernames [username1, username2, ...]')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Tên người dùng (tourist/student)', max_length=200)),
                ('content', modeldocker-compose downs.TextField(help_text='Nội dung bình luận')),
                ('images', models.JSONField(blank=True, default=list, help_text='Danh sách URLs hình ảnh (tối đa 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_reported', models.BooleanField(default=False, help_text='Đã bị báo cáo')),
                ('report_count', models.IntegerField(default=0, help_text='Số lần báo cáo')),
                ('reported_by', models.JSONField(blank=True, default=list, help_text='Danh sách user đã báo cáo')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='heritage.site')),
                ('user', models.ForeignKey(blank=True, help_text='User đã đăng nhập (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', '-created_at'], name='heritage_co_site_id_39670f_idx'), models.Index(fields=['user_name', '-created_at'], name='heritage_co_user_na_dd649b_idx'), models.Index(fields=['is_reported'], name='heritage_co_is_repo_ce5e18_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizBattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0, help_text='Tổng điểm')),
                ('correct_answers', models.IntegerField(default=0, help_text='Số câu đúng')),
                ('time_completed', models.IntegerField(blank=True, help_text='Tổng thời gian (giây)', null=True)),
                ('answers', models.JSONField(default=dict, help_text='Quiz ID -> {answer, is_correct, time_taken}')),
                ('rank', models.IntegerField(blank=True, help_text='Hạng (1-4)', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_participants', to='heritage.quizbattle')),
            ],
            options={
                'ordering': ['-score', 'time_completed'],
                'unique_together': {('battle', 'user_name')},
            },
        ),
    ]
