# Generated by Django 5.2.8 on 2025-11-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0014_quizbattle_comment_quizbattleparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('student', 'Học sinh'), ('tourist', 'Khách du lịch'), ('teacher', 'Giáo viên'), ('super_admin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
