# Generated by Django 5.2.8 on 2025-11-12 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0017_comment_quizbattleparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Tên người dùng (tourist/student)', max_length=200)),
                ('content', models.TextField(help_text='Nội dung bình luận')),
                ('images', models.JSONField(blank=True, default=list, help_text='Danh sách URLs hình ảnh (tối đa 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_reported', models.BooleanField(default=False, help_text='Đã bị báo cáo')),
                ('report_count', models.IntegerField(default=0, help_text='Số lần báo cáo')),
                ('reported_by', models.JSONField(blank=True, default=list, help_text='Danh sách user đã báo cáo')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='heritage.site')),
                ('user', models.ForeignKey(blank=True, help_text='User đã đăng nhập (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', '-created_at'], name='heritage_co_site_id_39670f_idx'), models.Index(fields=['user_name', '-created_at'], name='heritage_co_user_na_dd649b_idx'), models.Index(fields=['is_reported'], name='heritage_co_is_repo_ce5e18_idx')],
            },
        ),
    ]
